baseURL = 'https://raflywithme.my.id'
languageCode = 'en-us'
title = 'Muhammad Rafli'
theme = 'gokarna'
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
 footer = "Muhammad Rafli"
 description = "STUDENT OF SMK BIMA UTOMO BS"
 avatarURL = "/images/avatar.png"
 avatarSize = "size-m"
 
   customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """

# social links
  socialIcons = [
    {name = "facebook", url = "https://www.facebook.com/profile.php?id=100028098371144"},
    {name = "linkedin", url = "https://www.linkedin.com/in/muhammad-rafli-a2aa7a248"},
    {name = "github", url = "https://github.com/Rexdzx/"},
  ]
  metaKeywords = ["personal", "gokarna", "hugo", "blog"]

#menu links

[menu]
  [[menu.main]]
    name = "Beranda"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Tentang"
    pre = "<span data-feather='user'></span>"
    url = "/about/"
    weight = 40

  [[menu.main]]
    identifier = "github"
    url = "https://github.com"
    weight = 45
    # Using feather-icons
    pre = "<span data-feather='github'></span>"

  # [[menu.main]]
   # identifier = "language"
   # weight = 1
   # pre = "<span data-feather = 'globe'></span>"
